sudo: required
services:
  - docker

before_install:
  - docker build -t nicolasvanz/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nicolasvanz/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "sa-east-1"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-sa-east-1-601933675647"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY